### ISSUE TITLE
Auth for non admin not working

### ISSUE THREAD

**Issue by RemuxKid** [toddrob99/searcharr#1]
Various attempts on this. I am able to authenticate with the admin password, but not the non-admin password.

I tried making it 6 characters, no complex characters but still no luck :(

**Comment by toddrob99** [comment]
If you are already authenticated as an admin, you do not need to authenticate as a non-admin. Are you trying to authenticate as a non-admin for a user that is not already authenticated? If so what response do you get from the bot?

**Comment by RemuxKid** [comment]
This is true. A user which shouldn't have admin access is trying to authenticate.

The response I get back is "Incorrect password."

I then used the admin password and it worked.

I thought the password may be too complex so I simplified it to only letters, restarted the container, and deleted the DB. This still didn't work.

**Comment by toddrob99** [comment]
There are no minimum or maximum complexity requirements for the password, but it is case-sensitive. I have tested with full sentences including punctuation and it works fine. For example: `searcharr_password = "Authenticate me to use Searcharr!"` and `/start Authenticate me to use Searcharr!`.

The password probably should not include the bot's name. It should work, but not if the bot is mentioned in the message. The bot will strip out Telegram entities from the message--it will remove `/start` (or `/start:botName`) and any usernames that are mentioned. 

Make sure your password is not configured to start or end with a space.

The password can also be blank (`searcharr_password = ""`), and then simply `/start` will authenticate the user.

Have you tried the same password you're using for your admin password? If it works for admin authentication then it should work for non-admin authentication as well. Just make sure to change the admin password while you test, because the bot will check if the input matches the admin password first.

You might want to enable debug logging by including the `-v` flag when running the bot. If you're using docker-compose, add `command: python3 searcharr.py -v`  at the end and *recreate* the container (restarting isn't enough).

**Comment by RemuxKid** [comment]
Got this when adding that in:
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid top-level property "command". Valid top-level sections for this Compose file are: version, services, networks, volumes, and extensions starting with "x-".

**Comment by toddrob99** [comment]
It has to be indented on the same level as image, network mode, volumes, etc.

**Comment by RemuxKid** [comment]
`2020-11-09 18:50:01,795 -    DEBUG - searcharr(140683459513120):110 - Received start cmd from [MODIFIED[USER]]
2020-11-09 18:50:01,795 -    DEBUG - searcharr(140683459513120):736 - entities={<telegram.messageentity.MessageEntity object at 0x7ff36b65cdc0>: '/start', <telegram.messageentity.MessageEntity object at 0x7ff36ba1b8b0>: '5RWtEbAxyZ'}
2020-11-09 18:50:01,795 -    DEBUG - searcharr(140683459513120):740 - Stripped entities from message [/start 5RWtEbAxyZ]: []
2020-11-09 18:50:01,795 -    DEBUG - searcharr(140683459513120):908 - Executing query: [SELECT * FROM users WHERE id=?;] with args: [(566459207,)]...
2020-11-09 18:50:01,796 -    DEBUG - searcharr(140683459513120):955 - Database connection established [/app/data/searcharr.db].
2020-11-09 18:50:01,796 -    DEBUG - searcharr(140683459513120):921 - Query result for user lookup: None
2020-11-09 18:50:01,796 -    DEBUG - searcharr(140683459513120):926 - Did not find user [566459207] in the database.`

In the settings.py
`searcharr_password = "5RWtEbAxyZ"  # Used to authenticate as a regular user to add series/movies`

**Comment by RemuxKid** [comment]
Seems after removing and re-compiling I am not able to authenticate at all...

**Comment by toddrob99** [comment]
It's detecting the password as a Telegram entity that should be stripped from the message:

```
entities={<telegram.messageentity.MessageEntity object at 0x7ff36b65cdc0>: '/start', <telegram.messageentity.MessageEntity object at 0x7ff36ba1b8b0>: '5RWtEbAxyZ'}
Stripped entities from message [/start 5RWtEbAxyZ]: []
```

It is not doing that for me when I use the same password: 

```
entities={<telegram.messageentity.MessageEntity object at 0x04A12B38>: '/start'}
Stripped entities from message [/start 5RWtEbAxyZ]: [5RWtEbAxyZ]
```

I have no idea why Telegram would be parsing the password as an entity. What Telegram client are you using? Does the password look like normal plain text when you send?

I still find it very strange that the same password would work for admin authentication but would be stripped out as an entity for non-admin authentication. Both go through a single method to strip entities and check password validity. Are you doing anything differently when sending the /start command with admin vs. non-admin passwords?

**Comment by RemuxKid** [comment]
You're right.

I copied and pasted the passwords straight from the terminal. Formatting followed through with it which probably caused what you mentioned. It's all working now.

Thanks so much for your help <3
