### ISSUE TITLE
[REQUEST] Max daily request per user

### ISSUE THREAD

**Issue by RemuxKid** [toddrob99/searcharr#2]
It would be cool to assign users with X requests a day or so. Main purpose for this would be to limit abuse, and allows me to check HDD space before anyone requests a lot of things

**Comment by toddrob99** [comment]
Thanks for the suggestion, and for using Searcharr. This request is unlikely to be implemented, and will not be worked on at this time. Since Searcharr currently does not keep track of who is adding what, the level of effort to implement this request is too high compared to the benefit. If other users comment to support this request, or other functionality is added that makes this request easier to implement, this request can be re-opened for future consideration.
