### ISSUE TITLE
Nothing gets added

### ISSUE THREAD

**Issue by gr4z** [toddrob99/searcharr#8]
Whatever I search for, even though it says it has done it nothing gets added. Some logs
<removed logs>

**Comment by toddrob99** [comment]
Do you see any output when you run `docker logs searcharr`? It might be throwing an exception that's not hitting the log files. If there's no exception in the docker/console log, then I don't know what I can do to help troubleshoot this. I can see that it's successfully connecting to your Radarr instance because it it able to pull search results, and I see it is making the API call to add the movie (monitored=true and search=true). If it's not getting added to your Radarr instance at 192.168.10.30:7878, I have no idea why.

By the way, your Sonarr and Radarr API keys are in the logs. If your Sonarr or Radarr instances are accessible from the internet, you should generate new API keys in your Sonarr/Radarr settings.

**Comment by gr4z** [comment]
Sorted it, I was using a URL Base setting in both Radarr and Sonarr. Needed to add this to my settings.py URL links...and it works :) thanks for your bot.

**Comment by gr4z** [comment]
As above
