### ISSUE TITLE
REQ:  Ability to get a list of requested tv or movies.

### ISSUE THREAD

**Issue by famewolf** [toddrob99/searcharr#82]
Something like /list movies  or /list series and get a list of all the tv/movie titles so we can see at a glance if shows we plan to request are already requested.

**Comment by toddrob99** [comment]
This has been requested before, and I know Addarr has this feature. However, I do not intend to implement this in Searcharr. In my opinion, there is no elegant way to send a list of hundreds of items to a Telegram chat. Users would need to search the list for individual items anyway, so just use the Searcharr search command and the Add button will say it's already in the library if applicable. This also reduces the steps to check and add a movie, because you don't have to search the chat and then search with Searcharr before adding--you can just search once and add/cancel.
